version: '2'

volumes:
  db_data: {}

services:

  redis:
    image: redis:2.8.19
    hostname: redis

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.14-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  postgres:
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pushtogether

  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=pushtogether
      - USE_DOCKER=yes
    links:
      - postgres
      - rabbit
      - redis
    ports:
      - "8000:8000"
    command: /start.sh

  worker:
    << : *django
    volumes:
      - .:/app
    links:
      - postgres
      - rabbit
      - redis
    depends_on:
      - django
      - rabbit
    ports: []
    command: compose/local/worker/run_celery.sh

  flower:
    << : *django
    depends_on:
      - django
      - rabbit
      - redis
    volumes:
      - .:/app
    links:
      - rabbit
      - redis
    ports:
      - "8001:8001"
    command: compose/local/flower/start_flower.sh
