# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0014_auto_20171117_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='polis_id',
        ),
    ]
